export const peopleWokkiLang = [
  {
    whrascwo: "Lhuorwo Sorroohraanorworc",
    acwoahrracao: "172",
    scracc: "77",
    acraahrc_oaooanoorc: "rhanoowhwa",
    corahwh_oaooanoorc: "wwraahrc",
    worowo_oaooanoorc: "rhanhuwo",
    rhahrcaoac_roworarc: "19BBY",
    rrwowhwaworc: "scraanwo",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/1/",
    wwahanscc: [
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/2/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/3/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/6/",
    ],
    cakwooaahwoc: [],
    howoacahoaanwoc: [
      "acaoaoakc://cohraakah.wawoho/raakah/howoacahoaanwoc/14/",
      "acaoaoakc://cohraakah.wawoho/raakah/howoacahoaanwoc/30/",
    ],
    caorarccacahakc: [
      "acaoaoakc://cohraakah.wawoho/raakah/caorarccacahakc/12/",
      "acaoaoakc://cohraakah.wawoho/raakah/caorarccacahakc/22/",
    ],
    oarcworaaowowa: "2014-12-09T13:50:51.644000Z",
    wowaahaowowa: "2014-12-20T21:17:56.891000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/1/",
  },
  {
    whrascwo: "C-3PO",
    acwoahrracao: "167",
    scracc: "75",
    acraahrc_oaooanoorc: "wh/ra",
    corahwh_oaooanoorc: "rrooanwa",
    worowo_oaooanoorc: "rowoananoooh",
    rhahrcaoac_roworarc: "112BBY",
    rrwowhwaworc: "wh/ra",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/1/",
    wwahanscc: [
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/2/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/3/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/4/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/5/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/6/",
    ],
    cakwooaahwoc: ["acaoaoakc://cohraakah.wawoho/raakah/cakwooaahwoc/2/"],
    howoacahoaanwoc: [],
    caorarccacahakc: [],
    oarcworaaowowa: "2014-12-10T15:10:51.357000Z",
    wowaahaowowa: "2014-12-20T21:17:50.309000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/2/",
  },
  {
    whrascwo: "R2-D2",
    acwoahrracao: "96",
    scracc: "32",
    acraahrc_oaooanoorc: "wh/ra",
    corahwh_oaooanoorc: "ohacahaowo, rhanhuwo",
    worowo_oaooanoorc: "rcwowa",
    rhahrcaoac_roworarc: "33BBY",
    rrwowhwaworc: "wh/ra",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/8/",
    wwahanscc: [
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/2/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/3/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/4/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/5/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/6/",
    ],
    cakwooaahwoc: ["acaoaoakc://cohraakah.wawoho/raakah/cakwooaahwoc/2/"],
    howoacahoaanwoc: [],
    caorarccacahakc: [],
    oarcworaaowowa: "2014-12-10T15:11:50.376000Z",
    wowaahaowowa: "2014-12-20T21:17:50.311000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/3/",
  },
  {
    whrascwo: "Drarcaoac Vrawaworc",
    acwoahrracao: "202",
    scracc: "136",
    acraahrc_oaooanoorc: "whoowhwo",
    corahwh_oaooanoorc: "ohacahaowo",
    worowo_oaooanoorc: "rowoananoooh",
    rhahrcaoac_roworarc: "41.9BBY",
    rrwowhwaworc: "scraanwo",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/1/",
    wwahanscc: [
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/2/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/3/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/6/",
    ],
    cakwooaahwoc: [],
    howoacahoaanwoc: [],
    caorarccacahakc: [
      "acaoaoakc://cohraakah.wawoho/raakah/caorarccacahakc/13/",
    ],
    oarcworaaowowa: "2014-12-10T15:18:20.704000Z",
    wowaahaowowa: "2014-12-20T21:17:50.313000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/4/",
  },
  {
    whrascwo: "Lwoahra Orcrrrawhra",
    acwoahrracao: "150",
    scracc: "49",
    acraahrc_oaooanoorc: "rhrcooohwh",
    corahwh_oaooanoorc: "anahrracao",
    worowo_oaooanoorc: "rhrcooohwh",
    rhahrcaoac_roworarc: "19BBY",
    rrwowhwaworc: "wwwoscraanwo",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/2/",
    wwahanscc: [
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/2/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/3/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/6/",
    ],
    cakwooaahwoc: [],
    howoacahoaanwoc: [
      "acaoaoakc://cohraakah.wawoho/raakah/howoacahoaanwoc/30/",
    ],
    caorarccacahakc: [],
    oarcworaaowowa: "2014-12-10T15:20:09.791000Z",
    wowaahaowowa: "2014-12-20T21:17:50.315000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/5/",
  },
  {
    whrascwo: "Oohwowh Lrarcc",
    acwoahrracao: "178",
    scracc: "120",
    acraahrc_oaooanoorc: "rhrcooohwh, rrrcworo",
    corahwh_oaooanoorc: "anahrracao",
    worowo_oaooanoorc: "rhanhuwo",
    rhahrcaoac_roworarc: "52BBY",
    rrwowhwaworc: "scraanwo",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/1/",
    wwahanscc: [
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/5/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/6/",
    ],
    cakwooaahwoc: [],
    howoacahoaanwoc: [],
    caorarccacahakc: [],
    oarcworaaowowa: "2014-12-10T15:52:14.024000Z",
    wowaahaowowa: "2014-12-20T21:17:50.317000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/6/",
  },
  {
    whrascwo: "Bworchu Wacahaowochuwh anrarcc",
    acwoahrracao: "165",
    scracc: "75",
    acraahrc_oaooanoorc: "rhrcooohwh",
    corahwh_oaooanoorc: "anahrracao",
    worowo_oaooanoorc: "rhanhuwo",
    rhahrcaoac_roworarc: "47BBY",
    rrwowhwaworc: "wwwoscraanwo",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/1/",
    wwahanscc: [
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/5/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/6/",
    ],
    cakwooaahwoc: [],
    howoacahoaanwoc: [],
    caorarccacahakc: [],
    oarcworaaowowa: "2014-12-10T15:53:41.121000Z",
    wowaahaowowa: "2014-12-20T21:17:50.319000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/7/",
  },
  {
    whrascwo: "R5-D4",
    acwoahrracao: "97",
    scracc: "32",
    acraahrc_oaooanoorc: "wh/ra",
    corahwh_oaooanoorc: "ohacahaowo, rcwowa",
    worowo_oaooanoorc: "rcwowa",
    rhahrcaoac_roworarc: "huwhorwhooohwh",
    rrwowhwaworc: "wh/ra",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/1/",
    wwahanscc: ["acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/"],
    cakwooaahwoc: ["acaoaoakc://cohraakah.wawoho/raakah/cakwooaahwoc/2/"],
    howoacahoaanwoc: [],
    caorarccacahakc: [],
    oarcworaaowowa: "2014-12-10T15:57:50.959000Z",
    wowaahaowowa: "2014-12-20T21:17:50.321000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/8/",
  },
  {
    whrascwo: "Bahrrrrc Drarcoranahrracaoworc",
    acwoahrracao: "183",
    scracc: "84",
    acraahrc_oaooanoorc: "rhanraoaor",
    corahwh_oaooanoorc: "anahrracao",
    worowo_oaooanoorc: "rhrcooohwh",
    rhahrcaoac_roworarc: "24BBY",
    rrwowhwaworc: "scraanwo",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/1/",
    wwahanscc: ["acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/"],
    cakwooaahwoc: [],
    howoacahoaanwoc: [],
    caorarccacahakc: [
      "acaoaoakc://cohraakah.wawoho/raakah/caorarccacahakc/12/",
    ],
    oarcworaaowowa: "2014-12-10T15:59:50.509000Z",
    wowaahaowowa: "2014-12-20T21:17:50.323000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/9/",
  },
  {
    whrascwo: "Orhah-Wrawh Kwowhoorhah",
    acwoahrracao: "182",
    scracc: "77",
    acraahrc_oaooanoorc: "rahurhhurcwh, ohacahaowo",
    corahwh_oaooanoorc: "wwraahrc",
    worowo_oaooanoorc: "rhanhuwo-rrrcraro",
    rhahrcaoac_roworarc: "57BBY",
    rrwowhwaworc: "scraanwo",
    acooscwoohoorcanwa: "acaoaoakc://cohraakah.wawoho/raakah/akanrawhwoaoc/20/",
    wwahanscc: [
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/1/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/2/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/3/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/4/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/5/",
      "acaoaoakc://cohraakah.wawoho/raakah/wwahanscc/6/",
    ],
    cakwooaahwoc: [],
    howoacahoaanwoc: [
      "acaoaoakc://cohraakah.wawoho/raakah/howoacahoaanwoc/38/",
    ],
    caorarccacahakc: [
      "acaoaoakc://cohraakah.wawoho/raakah/caorarccacahakc/48/",
      "acaoaoakc://cohraakah.wawoho/raakah/caorarccacahakc/59/",
      "acaoaoakc://cohraakah.wawoho/raakah/caorarccacahakc/64/",
      "acaoaoakc://cohraakah.wawoho/raakah/caorarccacahakc/65/",
      "acaoaoakc://cohraakah.wawoho/raakah/caorarccacahakc/74/",
    ],
    oarcworaaowowa: "2014-12-10T16:16:29.192000Z",
    wowaahaowowa: "2014-12-20T21:17:50.325000Z",
    hurcan: "acaoaoakc://cohraakah.wawoho/raakah/akwoooakanwo/10/",
  },
];
